/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#ffb688",
        "on-secondary-fixed-variant": "#6200bc",
        "surface-container": "#1c2026",
        "surface-container-low": "#181c22",
        "on-surface-variant": "#c3c5d7",
        "on-surface": "#dfe2eb",
        "inverse-surface": "#dfe2eb",
        "inverse-primary": "#1653d6",
        "primary-fixed": "#dbe1ff",
        primary: "#b5c4ff",
        "secondary-fixed-dim": "#d8b9ff",
        "surface-dim": "#10141a",
        "secondary-fixed": "#eddcff",
        surface: "#10141a",
        "on-error": "#690005",
        "on-tertiary-container": "#471e00",
        "surface-tint": "#b5c4ff",
        error: "#ffb4ab",
        secondary: "#d8b9ff",
        "secondary-container": "#6e06d0",
        "on-secondary": "#450086",
        background: "#10141a",
        "tertiary-fixed-dim": "#ffb688",
        "on-primary": "#00297a",
        outline: "#8d90a0",
        "on-primary-fixed": "#00174c",
        "on-primary-fixed-variant": "#003dab",
        "tertiary-fixed": "#ffdbc7",
        "error-container": "#93000a",
        "inverse-on-surface": "#2d3137",
        "surface-container-highest": "#31353c",
        "surface-variant": "#31353c",
        "tertiary-container": "#e07313",
        "primary-fixed-dim": "#b5c4ff",
        "on-tertiary-fixed-variant": "#733600",
        "on-secondary-container": "#d5b5ff",
        "outline-variant": "#434654",
        "on-secondary-fixed": "#290055",
        "surface-container-lowest": "#0a0e14",
        "on-background": "#dfe2eb",
        "surface-bright": "#353940",
        "on-tertiary": "#512400",
        "on-error-container": "#ffdad6",
        "primary-container": "#638aff",
        "on-primary-container": "#00236b",
        "on-tertiary-fixed": "#311300",
        "surface-container-high": "#262a31",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
